### ISSUE TITLE
Cannot reproduce results on benchmark maze

### ISSUE THREAD

**Issue by ManuelEberhardinger** [facebookresearch/dcd#3]
Hey, 

I trained a model with the official hyperparameters you provided and the returned command by `python train_scripts/make_cmd.py --json minigrid/60_blocks_uniform/mg_60b_uni_accel_empty.json`. After fully training the model without any errors, I used the model to evaluate it on the benchmark maze. The table below shows the results of the model with the 20000 steps and also the final model, which was stored in `model.tar`. ACCEL 1 and ACCEL 2 are both models reported in the appendix of the published paper on page 25 Table 5: 

<table>
    <tr>
        <td>Level</td>
        <td>ACCEL 1</td>
        <td>ACCEL 2</td>
        <td>Model_20000.tar</td>
        <td>Model.tar</td>
    </tr>
    <tr>
        <td>Maze2</td>
        <td>0.93</td>
        <td>1.0</td>
        <td>0.45</td>
        <td>0.75</td>
    </tr>
    <tr>
        <td>LargeCorridor</td>
        <td>0.94</td>
        <td>1.0</td>
        <td>0.72</td>
        <td>0.48</td>
    </tr>
    <tr>
        <td>PerfectMazeMedium</td>
        <td>0.88</td>
        <td>0.93</td>
        <td>0.42</td>
        <td>0.46</td>
    </tr>
</table>

When I use the model after 20000 steps, which also the paper uses(if I understood it correctly), the results are only half as good as the published results. With the fully trained model the results are better but there is still a big gap.

Do you know what could be the reason for that? I thought that the RL policy is more stable because of the use of UED in reproducing the results.

I will also re-train the agent from scratch to see if the results are then reproducible, but this will take one week.

Thanks in advance!

**Comment by minqi** [comment]
Hi Manuel, can you share the output of your `meta.json` for this training run, generated in the results folder specified by `--log_dir`?

So I understand correctly, the columns `model_20000.tar` and `model.tar` are the results from models generated by your training run, which was started from scratch?

**Comment by ManuelEberhardinger** [comment]
Oh okay, I reported the `test_returns` which were printed by `eval.py` (see below output). How can I calculate the `solved_rate` then? I didn't found any args for the `solved_rate` in the `eval.py`-arguments.

Yes `model_20000.tar` and `model.tar` are the same model I trained from scratch. These was the output for both models:
```python
#python -m eval  --base_path workspaces/logs/accel --model_tar model_20000 --benchmark maze

test_returns:MultiGrid-Maze2-v0: 0.45 +/- 0.32
test_returns:MultiGrid-LargeCorridor-v0: 0.72 +/- 0.15
test_returns:MultiGrid-PerfectMazeMedium-v0: 0.42 +/- 0.39
test_returns:MultiGrid-PerfectMazeLarge-v0: 0.14 +/- 0.30
test_returns:MultiGrid-PerfectMazeXL-v0: 0.02 +/- 0.11
-----------------------------------------------------
| iq_test_returns:MultiGrid-L... | 0.71--0.75--0.77 |
| iq_test_returns:MultiGrid-M... | 0.11--0.50--0.76 |
| iq_test_returns:MultiGrid-P... | 0.00--0.00--0.00 |
| test_returns:MultiGrid-Larg... | 0.72 +/- 0.15    |
| test_returns:MultiGrid-Maze... | 0.45 +/- 0.32    |
| test_returns:MultiGrid-Perf... | 0.02 +/- 0.11    |
-----------------------------------------------------
```
```
#python -m eval  --base_path workspaces/logs/accel --model_tar model_20000 --benchmark maze

test_returns:MultiGrid-Maze2-v0: 0.45 +/- 0.32
test_returns:MultiGrid-LargeCorridor-v0: 0.72 +/- 0.15
test_returns:MultiGrid-PerfectMazeMedium-v0: 0.42 +/- 0.39
test_returns:MultiGrid-PerfectMazeLarge-v0: 0.14 +/- 0.30
test_returns:MultiGrid-PerfectMazeXL-v0: 0.02 +/- 0.11
-----------------------------------------------------
| iq_test_returns:MultiGrid-L... | 0.71--0.75--0.77 |
| iq_test_returns:MultiGrid-M... | 0.11--0.50--0.76 |
| iq_test_returns:MultiGrid-P... | 0.00--0.00--0.00 |
| test_returns:MultiGrid-Larg... | 0.72 +/- 0.15    |
| test_returns:MultiGrid-Maze... | 0.45 +/- 0.32    |
| test_returns:MultiGrid-Perf... | 0.02 +/- 0.11    |
-----------------------------------------------------```

**Comment by ManuelEberhardinger** [comment]
I think I found the problem, why I didn't had any solve rates reported... I need to set the accumulator to `mean`

**Comment by ManuelEberhardinger** [comment]
Hey Minqi,

I would have one more question about the level sampler, as I still have trouble understanding it properly. I attached a screenshot of the saved level screenshots every 1000 iterations and somehow, all images which have `n_edits > 0` are also `replay=True` and all levels which have no edits are not replayed. Could this be correct? 

I thought that when ACCEL edits a level than replay should be False as after editing it is a new level and not replayed from the LevelStore. Am I wrong in my assumption? 
I also restarted the training and took every 100 iterations a screenshot and there I can observe the same issue.

Thanks in advance!

![image](https://user-images.githubusercontent.com/14148740/207823110-1233d548-c67c-4dc7-b6a3-f84cb95dde60.png)

**Comment by minqi** [comment]
Hi Manuel, 

By default the current screenshot logic simply saves the image of the first level in a rollout batch of `num_processes` levels very `screenshot_interval` rollouts (each rollout being a PPO update cycle). That means the screenshot can occur on a rollout batch that is either using replay levels or new levels. 

This implementation of ACCEL edits levels after every replay rollout. The edited levels are then immediately evaluated, and only the edited levels that have higher PLR score than the lowest score in the level buffer will be added to the buffer. No screenshot logic applies to these edit evaluation rollouts. That means the only rollouts on edited levels for which screenshotting is applicable would be replay rollouts, when that edited level is sampled from the level buffer, as that is the only way the agent can visit an edited level.

**Comment by ManuelEberhardinger** [comment]
Thanks for the quick reply! Okay, that makes sense now!

But that also means that ACCEL has problems with catastrophic forgetting due to the many `n_edits=0` screenshots, since it has to revisit the levels without edits? Or is my interpretation wrong?

**Comment by minqi** [comment]
`n_edits=0` can result from screenshots of brand new levels sampled from the simulator (i.e. not a replay rollout) or if the agent replays a level from the level buffer that has not yet experienced an edit. The latter case would point to that level being especially challenging for the agent.

In general, I don't think you can read into the existence of `n_edits=0` screenshots as a sign of catastrophic forgetting.

**Comment by ManuelEberhardinger** [comment]
Thanks for the clarification! 

I also came to the conclusion when I evaluated the 20000 step and 25000 step models because the solved rate decreased significantly for the large corridor environment. I thought that one reason for this was the difference in the structure of the environment compared to the maze environment, and also that ACCEL creates more environments that look more like a maze than the large corridor. So I thought that the `n_edits=0` are also a sign for it. 

Level  | Model 20000 steps | Model 25000 steps
-- | -- | --
Maze2 | 0.82 | 1.00
LargeCorridor | 0.99 | 0.38
PerfectMazeMedium | 0.59 | 0.78

**Comment by minqi** [comment]
Yes, that is a plausible cause for this kind of instability in performance. The policy is also stochastic, so performance on many of the environments can have significant variance. 

You are right that the UED problem setting is a kind of continual learning, so catastrophic forgetting will play a role here. We briefly mentioned this connection in the concluding discussion of the Robust PLR paper: https://arxiv.org/abs/2110.02439

**Comment by ManuelEberhardinger** [comment]
Thank you very much! I will read the Robust PLR paper too. Now it all makes much more sense to me :)
