### ISSUE TITLE
commands error

### ISSUE THREAD

**Issue by wenjunli-0** [facebookresearch/dcd#4]
i think the value here should be False, as it's DR. 

https://github.com/facebookresearch/dcd/blob/0411f1fea3e6204a74c650ee725672a0dfd55444/train_scripts/grid_configs/bipedal/bipedal_dr.json#L38

**Comment by minqi** [comment]
For DR, we set `use_plr=True` with `level_replay_prob=0.0`. This ensures the same logical paths for generating levels is used across baselines.
